version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: magnhetic_db
      POSTGRES_USER: magnhetic_user
      POSTGRES_PASSWORD: magnhetic_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magnhetic_network

volumes:
  postgres_data:

networks:
  magnhetic_network:
    driver: bridge